<a href="https://colab.research.google.com/github/ClaireChiang91/A_100_Day_NLP_Challenge/blob/main/Day02_PytorchHW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
torch.from_array() / tensor.numpy()
torch.unsqueeze() / torch.squeeze()
tensor.transpose() / tensor.permute()
torch.reshape() / tensor.view()
"""

In [1]:
# Import torch and other required modules
import torch
import numpy as np

In [13]:
#Function 1: torch.from_array() / tensor.numpy()
# Example 1
a = np.random.rand(3,4,5,6)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [14]:
# Example 2 
a1 = np.random.randint(low=0, high=20, size=(2,3,5))
print(f'a1: {type(a1)}, {a1.dtype}')
b1 = torch.from_numpy(a1)
print(f'b1: {type(b1)}, {b1.dtype}')
c1 = torch.tensor(a1)
print(f'c1: {type(c1)}, {c1.dtype}')
d1 = c1.numpy()
print(f'd1: {type(d1)}, {d1.dtype}')

a1: <class 'numpy.ndarray'>, int64
b1: <class 'torch.Tensor'>, torch.int64
c1: <class 'torch.Tensor'>, torch.int64
d1: <class 'numpy.ndarray'>, int64


In [17]:
#Function 2: torch.unsqueeze() / torch.squeeze()
# Example 1
print('b',b.shape,'\n',b)
_g = torch.unsqueeze(b, dim=1) 
_h = torch.squeeze(_g) 
#print(_g.shape, _h.shape)
print('_g\n',_g.shape,'\n',_g)
print('_h\n',_h.shape,'\n',_h)

b torch.Size([3, 4, 5, 6]) 
 tensor([[[[3.1027e-01, 7.6174e-01, 9.6219e-01, 8.9888e-01, 9.3607e-01,
           8.7323e-02],
          [1.2418e-01, 2.5172e-01, 2.2905e-01, 6.7293e-01, 1.4409e-02,
           1.4150e-01],
          [7.6372e-01, 9.2602e-01, 7.9213e-01, 1.0683e-01, 1.6735e-01,
           3.1736e-01],
          [5.4435e-01, 6.7633e-01, 1.1763e-02, 8.5514e-01, 3.8141e-01,
           3.6468e-01],
          [4.9790e-01, 6.0903e-01, 9.9847e-02, 4.8649e-03, 3.7468e-01,
           4.4255e-01]],

         [[8.1885e-01, 2.7459e-01, 1.5035e-01, 3.7677e-01, 9.8146e-01,
           4.5224e-01],
          [9.8245e-01, 5.1943e-01, 1.1341e-01, 9.1073e-01, 7.0775e-01,
           6.2602e-01],
          [6.3585e-01, 4.5597e-01, 2.3153e-01, 3.1523e-02, 6.4894e-02,
           2.2366e-01],
          [9.7736e-01, 5.4615e-01, 6.7711e-01, 6.8806e-01, 9.9200e-01,
           4.4559e-01],
          [3.1393e-01, 3.2863e-01, 1.1884e-01, 3.2346e-01, 7.9500e-01,
           2.1294e-01]],

         [[3.9825

In [18]:
# Example 2
print('b',b.shape,'\n',b)
_g2 = torch.unsqueeze(b, dim=2) 
_h2 = torch.squeeze(_g2) 
#print(_g.shape, _h.shape)
print('_g2\n',_g2.shape,'\n',_g2)
print('_h2\n',_h2.shape,'\n',_h2)

b torch.Size([3, 4, 5, 6]) 
 tensor([[[[3.1027e-01, 7.6174e-01, 9.6219e-01, 8.9888e-01, 9.3607e-01,
           8.7323e-02],
          [1.2418e-01, 2.5172e-01, 2.2905e-01, 6.7293e-01, 1.4409e-02,
           1.4150e-01],
          [7.6372e-01, 9.2602e-01, 7.9213e-01, 1.0683e-01, 1.6735e-01,
           3.1736e-01],
          [5.4435e-01, 6.7633e-01, 1.1763e-02, 8.5514e-01, 3.8141e-01,
           3.6468e-01],
          [4.9790e-01, 6.0903e-01, 9.9847e-02, 4.8649e-03, 3.7468e-01,
           4.4255e-01]],

         [[8.1885e-01, 2.7459e-01, 1.5035e-01, 3.7677e-01, 9.8146e-01,
           4.5224e-01],
          [9.8245e-01, 5.1943e-01, 1.1341e-01, 9.1073e-01, 7.0775e-01,
           6.2602e-01],
          [6.3585e-01, 4.5597e-01, 2.3153e-01, 3.1523e-02, 6.4894e-02,
           2.2366e-01],
          [9.7736e-01, 5.4615e-01, 6.7711e-01, 6.8806e-01, 9.9200e-01,
           4.4559e-01],
          [3.1393e-01, 3.2863e-01, 1.1884e-01, 3.2346e-01, 7.9500e-01,
           2.1294e-01]],

         [[3.9825

In [12]:
#tensor.transpose() / tensor.permute()
# Example 1
print('b',b.shape,'\n',b)
_e=b.permute((0,3,2,1))
_f=b.transpose(1,3)
print('_e\n',_e.shape,'\n',_e)
print('_f\n',_f.shape,'\n',_f)

b torch.Size([1, 2, 3, 3]) 
 tensor([[[[0.1641, 0.4758, 0.5988],
          [0.0228, 0.9223, 0.7119],
          [0.3525, 0.9048, 0.4094]],

         [[0.6149, 0.6657, 0.6025],
          [0.7220, 0.3267, 0.5039],
          [0.1091, 0.5691, 0.7346]]]], dtype=torch.float64)
_e
 torch.Size([1, 3, 3, 2]) 
 tensor([[[[0.1641, 0.6149],
          [0.0228, 0.7220],
          [0.3525, 0.1091]],

         [[0.4758, 0.6657],
          [0.9223, 0.3267],
          [0.9048, 0.5691]],

         [[0.5988, 0.6025],
          [0.7119, 0.5039],
          [0.4094, 0.7346]]]], dtype=torch.float64)
_f
 torch.Size([1, 3, 3, 2]) 
 tensor([[[[0.1641, 0.6149],
          [0.0228, 0.7220],
          [0.3525, 0.1091]],

         [[0.4758, 0.6657],
          [0.9223, 0.3267],
          [0.9048, 0.5691]],

         [[0.5988, 0.6025],
          [0.7119, 0.5039],
          [0.4094, 0.7346]]]], dtype=torch.float64)


In [19]:
# Example 2
print('b',b.shape,'\n',b)
_e2=b.permute((3,1,2,0))
_f2=b.transpose(0,3)
print('_e2\n',_e2.shape,'\n',_e2)
print('_f2\n',_f2.shape,'\n',_f2)

b torch.Size([3, 4, 5, 6]) 
 tensor([[[[3.1027e-01, 7.6174e-01, 9.6219e-01, 8.9888e-01, 9.3607e-01,
           8.7323e-02],
          [1.2418e-01, 2.5172e-01, 2.2905e-01, 6.7293e-01, 1.4409e-02,
           1.4150e-01],
          [7.6372e-01, 9.2602e-01, 7.9213e-01, 1.0683e-01, 1.6735e-01,
           3.1736e-01],
          [5.4435e-01, 6.7633e-01, 1.1763e-02, 8.5514e-01, 3.8141e-01,
           3.6468e-01],
          [4.9790e-01, 6.0903e-01, 9.9847e-02, 4.8649e-03, 3.7468e-01,
           4.4255e-01]],

         [[8.1885e-01, 2.7459e-01, 1.5035e-01, 3.7677e-01, 9.8146e-01,
           4.5224e-01],
          [9.8245e-01, 5.1943e-01, 1.1341e-01, 9.1073e-01, 7.0775e-01,
           6.2602e-01],
          [6.3585e-01, 4.5597e-01, 2.3153e-01, 3.1523e-02, 6.4894e-02,
           2.2366e-01],
          [9.7736e-01, 5.4615e-01, 6.7711e-01, 6.8806e-01, 9.9200e-01,
           4.4559e-01],
          [3.1393e-01, 3.2863e-01, 1.1884e-01, 3.2346e-01, 7.9500e-01,
           2.1294e-01]],

         [[3.9825

In [26]:
c.shape

torch.Size([3, 4, 5, 6])

In [27]:
#torch.reshape() / tensor.view()
# Example 1
_b3=c.reshape(12,30)
_c3=c.view(12,30)
_d3=c.reshape(3,4,-1)
print(_b3.shape, _c3.shape,_d3.shape)
_b3,_c3,_d3

torch.Size([12, 30]) torch.Size([12, 30]) torch.Size([3, 4, 30])


(tensor([[3.1027e-01, 7.6174e-01, 9.6219e-01, 8.9888e-01, 9.3607e-01, 8.7323e-02,
          1.2418e-01, 2.5172e-01, 2.2905e-01, 6.7293e-01, 1.4409e-02, 1.4150e-01,
          7.6372e-01, 9.2602e-01, 7.9213e-01, 1.0683e-01, 1.6735e-01, 3.1736e-01,
          5.4435e-01, 6.7633e-01, 1.1763e-02, 8.5514e-01, 3.8141e-01, 3.6468e-01,
          4.9790e-01, 6.0903e-01, 9.9847e-02, 4.8649e-03, 3.7468e-01, 4.4255e-01],
         [8.1885e-01, 2.7459e-01, 1.5035e-01, 3.7677e-01, 9.8146e-01, 4.5224e-01,
          9.8245e-01, 5.1943e-01, 1.1341e-01, 9.1073e-01, 7.0775e-01, 6.2602e-01,
          6.3585e-01, 4.5597e-01, 2.3153e-01, 3.1523e-02, 6.4894e-02, 2.2366e-01,
          9.7736e-01, 5.4615e-01, 6.7711e-01, 6.8806e-01, 9.9200e-01, 4.4559e-01,
          3.1393e-01, 3.2863e-01, 1.1884e-01, 3.2346e-01, 7.9500e-01, 2.1294e-01],
         [3.9825e-01, 8.6080e-01, 5.7963e-01, 9.4029e-01, 5.3522e-01, 5.3250e-01,
          7.8991e-01, 7.1369e-01, 3.3534e-02, 7.8280e-01, 3.7336e-01, 1.3359e-01,
          1.90

In [28]:
# Example 2
_b5=c.reshape(12,5,6)
_c5=c.view(12,5,6)
_d5=c.reshape(12,-1)
print(_b5.shape, _c5.shape,_d5.shape)
_b5,_c5,_d5

torch.Size([12, 5, 6]) torch.Size([12, 5, 6]) torch.Size([12, 30])


(tensor([[[3.1027e-01, 7.6174e-01, 9.6219e-01, 8.9888e-01, 9.3607e-01,
           8.7323e-02],
          [1.2418e-01, 2.5172e-01, 2.2905e-01, 6.7293e-01, 1.4409e-02,
           1.4150e-01],
          [7.6372e-01, 9.2602e-01, 7.9213e-01, 1.0683e-01, 1.6735e-01,
           3.1736e-01],
          [5.4435e-01, 6.7633e-01, 1.1763e-02, 8.5514e-01, 3.8141e-01,
           3.6468e-01],
          [4.9790e-01, 6.0903e-01, 9.9847e-02, 4.8649e-03, 3.7468e-01,
           4.4255e-01]],
 
         [[8.1885e-01, 2.7459e-01, 1.5035e-01, 3.7677e-01, 9.8146e-01,
           4.5224e-01],
          [9.8245e-01, 5.1943e-01, 1.1341e-01, 9.1073e-01, 7.0775e-01,
           6.2602e-01],
          [6.3585e-01, 4.5597e-01, 2.3153e-01, 3.1523e-02, 6.4894e-02,
           2.2366e-01],
          [9.7736e-01, 5.4615e-01, 6.7711e-01, 6.8806e-01, 9.9200e-01,
           4.4559e-01],
          [3.1393e-01, 3.2863e-01, 1.1884e-01, 3.2346e-01, 7.9500e-01,
           2.1294e-01]],
 
         [[3.9825e-01, 8.6080e-01, 5.7963e-0